/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import Controller.RelatorioController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.modelRelatorio;

/**
 *
 * @author Administrador
 */
public class Relatorio extends javax.swing.JFrame {
    
    private final RelatorioController relatorioController;

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        relatorioController = new RelatorioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPesquisarData = new javax.swing.JTextField();
        jTextFieldPesquisarId = new javax.swing.JTextField();
        jButtonPesquisarData = new javax.swing.JButton();
        jButtonDeletarPorId = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel3.setText("Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));
        getContentPane().add(jTextFieldPesquisarData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 150, -1));
        getContentPane().add(jTextFieldPesquisarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 160, -1));

        jButtonPesquisarData.setText("Pesquisar");
        jButtonPesquisarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarDataActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jButtonDeletarPorId.setText("Deletar");
        jButtonDeletarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarPorIdActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletarPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 90, -1));

        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "cliente", "servico", "valor", "hora", "data", "obs"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 1150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1405, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarDataActionPerformed
        // Obtém a data do campo de texto
        String data = jTextFieldPesquisarData.getText();

        // Obtém relatórios do controlador
        List<modelRelatorio> relatorios = relatorioController.getRelatoriosByData(data);

        // Preenche a tabela com os relatórios obtidos
        DefaultTableModel tabelaRelatorio = (DefaultTableModel) jTableRelatorio.getModel();
        tabelaRelatorio.setRowCount(0); // Limpa a tabela antes de preenchê-la novamente

        for (modelRelatorio relatorio : relatorios) {
            Object[] dados = {
                relatorio.getId(),
                relatorio.getCliente(),
                relatorio.getServico(),
                relatorio.getValor(),
                relatorio.getData(),
                relatorio.getHora(),
                relatorio.getObservacao()
            };
            tabelaRelatorio.addRow(dados);
        }
    }//GEN-LAST:event_jButtonPesquisarDataActionPerformed

    private void jButtonDeletarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarPorIdActionPerformed
        // Obtém o ID do campo de texto
                
        int id = Integer.parseInt(jTextFieldPesquisarId.getText());

        // Deleta o relatório por ID
        relatorioController.deletarRelatorioPorId(id);

        // Atualiza a tabela após a exclusão
        jButtonPesquisarDataActionPerformed(evt);

    }//GEN-LAST:event_jButtonDeletarPorIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletarPorId;
    private javax.swing.JButton jButtonPesquisarData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorio;
    private javax.swing.JTextField jTextFieldPesquisarData;
    private javax.swing.JTextField jTextFieldPesquisarId;
    // End of variables declaration//GEN-END:variables
}
